on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: main
    paths:
      - data/theatres.csv
  workflow_dispatch:

name: Render

jobs:
  render:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::here
            any::data.table
            any::ggplot2
            any::ggtext
            any::scales
            any::lubridate
            any::showtext
            any::svglite
      - shell: bash
        run: Rscript scripts/imdb-ratings.r
      - shell: bash
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add media/* || echo "No changes to add"
          git commit -m 'ci: render figures' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
